In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("./2021실거래가.csv",encoding='CP949')

In [3]:
df.head()

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
0,서울특별시 강남구 개포동,655-2,655.0,2.0,개포2차현대아파트(220),77.75,202104,15,"174,000",9,1988,언주로 103,NaN,-,-
1,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202105,15,"195,000",5,1987,언주로 3,NaN,-,-
2,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202108,11,"200,000",3,1987,언주로 3,NaN,-,-
3,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202109,2,"220,000",2,1987,언주로 3,NaN,-,-
4,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202112,4,"215,000",3,1987,언주로 3,NaN,중개거래,서울 강남구

In [4]:
df.dropna(axis=0,subset=['본번','부번'],inplace=True)

In [5]:
df.astype({'본번':int,'부번':int})

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,202104,15,"174,000",9,1988,언주로 103,NaN,-,-
1,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,202105,15,"195,000",5,1987,언주로 3,NaN,-,-
2,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,202108,11,"200,000",3,1987,언주로 3,NaN,-,-
3,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,202109,2,"220,000",2,1987,언주로 3,NaN,-,-
4,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,202112,4,"215,000",3,1987,언주로 3,NaN,중개거래,서울 강남구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43413,서울특별시 중랑구 중화동,274-51,274,51,한영(101),57.66,202102,27,"30,500",5,2003,동일로144길 74,NaN,-,-
43414,서울특별시 중랑구 중화동,274-51,274,51,한영(101),84.69,202111,4,"50,000",2,2003,동일로144길 74,NaN,중개거래,"서울 송파구, 서울 중랑구"
43415,서울특별시 중랑구 중화동,274-75,274,75,한영(102),72.22,202105,4,"49,500",4,2003,동일로144길 74,NaN,-,-
43416,서울특별시 중랑구 중화동,274-76,274,76,한영(103),58.46,202107,1,"30,000",2,2003,동일로144길 74,NaN,-,-
43417,서울특별시 중랑구 중화동,274-76,274,76,한영(103),104.93,202108,20,"61,500",7,2003,동일로144길 74,NaN,-,-

In [6]:
df.insert(0,'계약일자',df['계약년월']*100+df['계약일'])
##df['계약일']=df['계약년월']*100+df['계약일']
df.drop(labels='계약년월',axis=1,inplace=True)
df.drop(labels='계약일',axis=1,inplace=True)

In [7]:
df.head()

,계약일자,시군구,번지,본번,부번,단지명,전용면적(㎡),거래금액(만원),층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
0,20210415,서울특별시 강남구 개포동,655-2,655.0,2.0,개포2차현대아파트(220),77.75,"174,000",9,1988,언주로 103,NaN,-,-
1,20210515,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,"195,000",5,1987,언주로 3,NaN,-,-
2,20210811,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,"200,000",3,1987,언주로 3,NaN,-,-
3,20210902,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,"220,000",2,1987,언주로 3,NaN,-,-
4,20211204,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,"215,000",3,1987,언주로 3,NaN,중개거래,서울 강남구

In [8]:
df.insert(1,'구',df['시군구'])
df.insert(2,'동',df['시군구'])
df.drop(labels='시군구',axis=1,inplace=True)
df.drop(labels='중개사소재지',axis=1,inplace=True)

In [9]:
df.head()

,계약일자,구,동,번지,본번,부번,단지명,전용면적(㎡),거래금액(만원),층,건축년도,도로명,해제사유발생일,거래유형
0,20210415,서울특별시 강남구 개포동,서울특별시 강남구 개포동,655-2,655.0,2.0,개포2차현대아파트(220),77.75,"174,000",9,1988,언주로 103,NaN,-
1,20210515,서울특별시 강남구 개포동,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,"195,000",5,1987,언주로 3,NaN,-
2,20210811,서울특별시 강남구 개포동,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,"200,000",3,1987,언주로 3,NaN,-
3,20210902,서울특별시 강남구 개포동,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,"220,000",2,1987,언주로 3,NaN,-
4,20211204,서울특별시 강남구 개포동,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,"215,000",3,1987,언주로 3,NaN,중개거래

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43413 entries, 0 to 43417
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   계약일자      43413 non-null  int64
 1   구         43413 non-null  object
 2   동         43413 non-null  object
 3   번지        43404 non-null  object
 4   본번        43413 non-null  float64
 5   부번        43413 non-null  float64
 6   단지명       43413 non-null  object
 7   전용면적(㎡)   43413 non-null  float64
 8   거래금액(만원)  43413 non-null  object
 9   층         43413 non-null  int64
 10  건축년도      43413 non-null  int64
 11  도로명       43413 non-null  object
 12  해제사유발생일   1468 non-null   float64
 13  거래유형      43413 non-null  object
dtypes: float64(4), int64(3), object(7)
memory usage: 5.0+ MB

In [11]:
##여기 범위에 숫자만 info 보고 숫자 넣어 주세요
for i in range(0,43413):
    str1=df.iloc[i,1]
    str2=str1.split()
    df.iloc[i,1]=str2[1]
    df.iloc[i,2]=str2[2]
    str3=df.iloc[i,8]
    str4=str3.split(',')
    df.iloc[i,8]="".join(str4)

In [13]:
df.astype({"거래금액(만원)":int})

,계약일자,구,동,번지,본번,부번,단지명,전용면적(㎡),거래금액(만원),층,건축년도,도로명,해제사유발생일,거래유형
0,20210415,강남구,개포동,655-2,655.0,2.0,개포2차현대아파트(220),77.75,174000,9,1988,언주로 103,NaN,-
1,20210515,강남구,개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,195000,5,1987,언주로 3,NaN,-
2,20210811,강남구,개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,200000,3,1987,언주로 3,NaN,-
3,20210902,강남구,개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,220000,2,1987,언주로 3,NaN,-
4,20211204,강남구,개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,215000,3,1987,언주로 3,NaN,중개거래
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43413,20210227,중랑구,중화동,274-51,274.0,51.0,한영(101),57.66,30500,5,2003,동일로144길 74,NaN,-
43414,20211104,중랑구,중화동,274-51,274.0,51.0,한영(101),84.69,50000,2,2003,동일로144길 74,NaN,중개거래
43415,20210504,중랑구,중화동,274-75,274.0,75.0,한영(102),72.22,49500,4,2003,동일로144길 74,NaN,-
43416,20210701,중랑구,중화동,274-76,274.0,76.0,한영(103),58.46,30000,2,2003,동일로144길 74,NaN,-
43417,20210820,중랑구,중화동,274-76,274.0,76.0,한영(103),104.93,61500,7,2003,동일로144길 74,NaN,-

In [14]:
df.head()

,계약일자,구,동,번지,본번,부번,단지명,전용면적(㎡),거래금액(만원),층,건축년도,도로명,해제사유발생일,거래유형
0,20210415,강남구,개포동,655-2,655.0,2.0,개포2차현대아파트(220),77.75,174000,9,1988,언주로 103,NaN,-
1,20210515,강남구,개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,195000,5,1987,언주로 3,NaN,-
2,20210811,강남구,개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,200000,3,1987,언주로 3,NaN,-
3,20210902,강남구,개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,220000,2,1987,언주로 3,NaN,-
4,20211204,강남구,개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,215000,3,1987,언주로 3,NaN,중개거래

In [15]:
df.to_csv("2021실거래가_처리후.csv",encoding='cp949',index=False)